# Generated by Django 2.0.2 on 2018-02-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_album_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_types',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
